# docker-compose.yml
version: '3.8'

services:
  vite-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Map Nginx port to localhost port
    container_name: vite-react-app
